<?php

namespace App\Admin\Controllers;

use App\Labels\OrderLabel;
use Dcat\Admin\Http\Controllers\AdminController;
use Dcat\Admin\Layout\Content;
use Dcat\Admin\Traits\HasUploadedFile;

class UploadController extends AdminController
{
    use HasUploadedFile;

    public function index(Content $content)
    {
        $label = new OrderLabel(['numbers' => [2]]);

        $pdf = $label->generate();
        $now_time = date('YmdHis');
        $labelFilename =  $now_time . ".pdf";
        $filepath = storage_path("app/public/handover-lists/" . $labelFilename);
        $pdf->Output($filepath, 'I');
        //return parent::index($content); // TODO: Change the autogenerated stub
    }


}
