<?php

namespace App\Admin\Extendsions\Tools;

use App\Admin\Renderable\BatchStockOperation;
use App\Admin\Renderable\StockTable;
use App\Models\Stock;
use Dcat\Admin\Grid\BatchAction;
use Dcat\Admin\Widgets\DialogForm;
use Dcat\Admin\Widgets\Modal;
use Illuminate\Http\Request;
use Symfony\Component\Console\Input\Input;

class BatchAddStock extends BatchAction
{
    protected $action;

    public function __construct($title = null)
    {
        $this->title = $title;
    }
    public function render()
    {
        /*return Modal::make()
            ->lg()
            ->title('批量库存操作')
            ->body(BatchStockOperation::make())
            ->button('批量库存操作');*/
        return parent::render(); // TODO: Change the autogenerated stub
    }

    // 确认弹窗信息
    public function confirm()
    {

        //dd($this->getKey());
        return '您确定要批量删除吗？';
    }

    // 处理请求
    public function handle(Request $request)
    {
        $keys = $this->getKey();
        dd($keys);
        return Modal::make()
            ->lg()
            ->title('批量库存操作')
            ->body(BatchStockOperation::make())
            ->button('批量库存操作');

        // 获取选中的文章ID数组
        $keys = $this->getKey();

        // 获取请求参数
        //$action = $request->get('action');

        /** @var Stock $stock */
        foreach (Stock::find($keys) as $stock) {
            $stock->delete();
        }


        return $this->response()->success("")->refresh();
    }

    // 设置请求参数
    public function parameters()
    {
        return [
            'action' => $this->action,
        ];
    }
}
